apiVersion: v1
kind: ConfigMap
metadata:
  name: installer-config
  namespace: default
data:
  install.sh: |
    #!/bin/bash

    set -ex

    backend_ip=${BACKEND_IP}
    frontend_container_cores_num=${FRONTEND_CONTAINER_CORES_NUM}
    mount_point=${MOUNT_POINT}
    filesystem_name=${FILESYSTEM_NAME}

    echo "$(date -u): starting weka agent installation"

    function retry {
      local retry_max=$1
      local retry_sleep=$2
      shift 2
      local count=$retry_max
      while [ $count -gt 0 ]; do
          "$@" && break
          count=$(($count - 1))
          echo "Retrying $* in $retry_sleep seconds..."
          sleep $retry_sleep
      done

      [ $count -eq 0 ] && {
          echo "Retry failed [$retry_max]: $*"
          echo "$(date -u): retry failed"
          return 1
      }
      return 0
    }

    retry 60 45 curl --fail -o install_script.sh $backend_ip:14000/dist/v1/install
    chmod +x install_script.sh
    ./install_script.sh
    echo "$(date -u): weka agent installation complete"

    echo "$(date -u): retrying wekafs mount..."

    mkdir -p $mount_point
    mount_command="mount -t wekafs -o net=udp -o num_cores=$frontend_container_cores_num $backend_ip/$filesystem_name $mount_point"
    echo "$mount_command" > /tmp/mount_command
    retry 60 45 $mount_command

    echo "$(date -u): wekafs mount complete"
